# Generated by Django 6.0.1 on 2026-04-11 19:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacenes',
            fields=[
                ('id_almacen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_almacen', models.CharField(max_length=60)),
                ('descripcion_almacen', models.CharField(max_length=150)),
                ('direccion_almacen', models.CharField(max_length=120)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'almacences',
            },
        ),
        migrations.CreateModel(
            name='CargoColaboradores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=60)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cargo_colaboradores',
            },
        ),
        migrations.CreateModel(
            name='EstadoColaboradores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=20)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'estado_colaboradores',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='TipoEstadoItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=60)),
                ('descripcion_estado', models.CharField(max_length=150)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipo_estado_items',
            },
        ),
        migrations.CreateModel(
            name='TipoItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=60)),
                ('decripcion_tipo', models.CharField(max_length=150)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipo_items',
            },
        ),
        migrations.CreateModel(
            name='TipoMoneda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('logo', models.CharField(max_length=1)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipo_moneda',
            },
        ),
        migrations.CreateModel(
            name='TiposInsumo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('denominacion', models.CharField(max_length=40)),
                ('cuenta_contable_haber', models.CharField(max_length=20)),
                ('cuenta_contable_debe', models.CharField(max_length=20)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipos_insumo',
            },
        ),
        migrations.CreateModel(
            name='TiposMovimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_movimiento', models.CharField(max_length=60)),
                ('decripcion_tipo', models.CharField(max_length=150)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipos_movimiento',
                'ordering': ['nombre_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_colaborador', models.CharField(max_length=150)),
                ('usuario_sistema', models.CharField(max_length=25)),
                ('correo', models.CharField(max_length=50)),
                ('usuario_sentinel', models.CharField(max_length=15)),
                ('usuario_sbs', models.CharField(max_length=15)),
                ('usuario_windows', models.CharField(max_length=15)),
                ('usuario_reloj_control', models.CharField(max_length=15)),
                ('codigo_impresion_colaborador', models.CharField(max_length=20)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cargo_colaborador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_logistica.cargocolaboradores')),
                ('estado_colaboradores', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_logistica.estadocolaboradores')),
            ],
            options={
                'db_table': 'colaboradores',
            },
        ),
        migrations.CreateModel(
            name='ItemMovimientosCabecera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('firma_base64', models.TextField()),
                ('hash_seguridad', models.CharField(editable=False, max_length=64)),
                ('pdf_archivo', models.FileField(blank=True, null=True, upload_to='pdfs_movimientos/')),
                ('colaborador_confirma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_logistica.colaboradores')),
            ],
            options={
                'db_table': 'items_movimientos_cabezera',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comprobante_contable', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_contable', models.DateField(blank=True, null=True)),
                ('factura_boleta', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_item', models.CharField(max_length=100)),
                ('marca_item', models.CharField(blank=True, max_length=20, null=True)),
                ('modelo_item', models.CharField(blank=True, max_length=20, null=True)),
                ('serie_item', models.CharField(blank=True, max_length=20, null=True)),
                ('imagen_qr', models.ImageField(blank=True, null=True, upload_to='imagenes_qr/')),
                ('cantidad_items', models.IntegerField(default=0)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_logistica.almacenes')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_logistica.colaboradores')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_logistica.proveedores')),
                ('id_estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_logistica.tipoestadoitems')),
                ('tipo_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_logistica.tipoitems')),
                ('tipo_moneda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_logistica.tipomoneda')),
                ('tipo_insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_logistica.tiposinsumo')),
            ],
            options={
                'db_table': 'items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistorialInventarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_almacen', models.CharField(max_length=60)),
                ('nombre_usuario', models.CharField(max_length=150)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_logistica.items')),
            ],
            options={
                'db_table': 'historial_inventarios',
            },
        ),
        migrations.CreateModel(
            name='ItemsMovimientos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('voucher', models.CharField(blank=True, max_length=15, null=True)),
                ('referencia', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_contable', models.DateField(blank=True, null=True)),
                ('factura', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre_origen', models.CharField(blank=True, max_length=150, null=True)),
                ('nombre_destino', models.CharField(max_length=150)),
                ('cantidad_movimiento', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.CharField(default='Sin Observaciones', max_length=200)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_logistica.items')),
                ('id_movimiento_cabezera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_logistica.itemmovimientoscabecera')),
                ('id_movimiento_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_logistica.itemsmovimientos')),
                ('tipo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_logistica.tiposmovimiento')),
            ],
            options={
                'db_table': 'items_movimientos',
            },
        ),
    ]
