# Generated by Django 6.0.1 on 2026-03-14 01:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logistica', '0006_rename_id_cabezera_itemmovimientoscabecera_id_cabecera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=120)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='TipoMoneda',
            fields=[
                ('ip_tipo_moneda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('logo', models.CharField(max_length=1)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipo_moneda',
            },
        ),
        migrations.RemoveField(
            model_name='items',
            name='descripcion_item',
        ),
        migrations.AddField(
            model_name='items',
            name='marca_item',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='modelo_item',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='items',
            name='serie_item',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='itemsmovimientos',
            name='factura',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='itemsmovimientos',
            name='fecha_contable',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemsmovimientos',
            name='referencia',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='itemsmovimientos',
            name='voucher',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='cantidad_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='items',
            name='tipo_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_logistica.tipoitems'),
        ),
        migrations.AlterField(
            model_name='itemsmovimientos',
            name='cantidad_movimiento',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='itemsmovimientos',
            name='id_movimiento_cabezera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_logistica.itemmovimientoscabecera'),
        ),
        migrations.AlterField(
            model_name='itemsmovimientos',
            name='tipo_movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_logistica.tiposmovimiento'),
        ),
        migrations.AddField(
            model_name='items',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_logistica.proveedores'),
        ),
        migrations.AddField(
            model_name='items',
            name='tipo_moneda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_logistica.tipomoneda'),
        ),
    ]
