# Generated by Django 6.0.1 on 2026-03-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logistica', '0009_alter_items_id_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='comprobante_contable',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='factura_boleta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='fecha_contable',
            field=models.DateField(blank=True, null=True),
        ),
    ]
