# Generated by Django 6.0.1 on 2026-03-15 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logistica', '0010_items_comprobante_contable_items_factura_boleta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsmovimientos',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_logistica.proveedores'),
        ),
    ]
