# Generated by Django 6.0.1 on 2026-03-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seguimiento_actividades', '0002_estadotareas_alter_subtareas_fin_actividad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtareas',
            name='detalle_subtarea',
            field=models.TextField(max_length=350),
        ),
    ]
