from django.urls import path
from . import views


urlpatterns = [
    path('',views.logistica_items,name='logistica_items'),
    path('agregar-item-tipo-item',views.agregar_item_tipo_item,name='agregar_item_tipo_item'),
    path('agregar-stock/<int:pk>/',views.agregar_item_stock,name='agregar_item_stock'),
    path('agregar-serializable/<int:pk>/',views.agregar_item_serializable,name='agregar_item_serializable'),
    path('seleccionar-proveedor/',views.seleccionar_proveedor,name='seleccionar_proveedor'),
    path('buscar-proveedor/',views.buscar_proveedor,name='buscar_proveedor'),
    path('agregar-proveedor/',views.agregar_proveedor,name='agregar_proveedor'),
    path('editar-item/<int:pk>/',views.editar_item,name='editar_item'),
    #path('editar-item-celular/<int:pk>/',views.editar_item_celular,name='editar_item_celular'),
    path('inventariar-articulo/<int:pk>/',views.inventariar_articulo,name='inventariar_articulo'),
    path('eliminar-articulo/<int:pk>/',views.eliminar_articulo,name='eliminar_articulo'),
    path('historial-inventario-articulo/<int:pk>/',views.historial_inventario_articulo,name='historial_inventario_articulo'),
    path('movimientos-articulo/<int:pk>/',views.movimientos_articulo,name='movimientos_articulo'),
    #path('',views.logistica_almacenes,name='logistica_items'),
    path('almacenes',views.logistica_almacenes,name='logistica_almacenes'),
    path('agregar-almacenes',views.agregar_almacenes,name='agregar_almacenes'),
    path('editar-almacen/<int:pk>/',views.editar_almacen,name='editar_almacen'),
    path('eliminar-almacen/<int:pk>/',views.eliminar_almacen,name='eliminar_almacen'),
    path('items-por-almace/<int:pk>/',views.items_por_almacen,name='items_por_almacen'),
    path('movimientos',views.logistica_movimientos,name='logistica_movimientos'),
    path('agregar-movimiento',views.agregar_movimientos,name='agregar_movimientos'),
    path('filtrar-campos-movimientos',views.filtrar_campos_movimientos,name='filtrar_campos_movimientos'),
    path('imprimir-pdf-movimientos-firmado/<int:pk>/',views.imprimir_pdf_movimientos_firmado,name='imprimir_pdf_movimientos_firmado'),
    path('imprimir-pdf-qrs',views.imprimir_pdf_qrs,name='imprimir_pdf_qrs'),
    path('agregar-fila-item',views.agregar_fila_item,name='agregar_fila_item'),
    path('historial-inventario',views.logistica_historial_inventario,name='logistica_historial_inventario'),
    path('articulos-no-inventariados',views.articulos_no_inventariados,name='articulos_no_inventariados'),
    path('colaboradores',views.logistica_colaboradores,name='logistica_colaboradores'),    
    path('movimientos-por-item/<int:pk>/',views.movimientos_por_item,name='movimientos_por_item'),
    path('movimientos-por-colaborador/<int:pk>/',views.movimientos_por_colaborador,name='movimientos_por_colaborador'),
    path('login',views.login_logistica,name='login_logistica'),
    path('logout',views.logout_logistica,name='logout_logistica'),    
]
